import { z } from 'zod';

export const ErrorCode = {
  CAMPAIGN_NOT_FOUND: 'CAMPAIGN_NOT_FOUND',
  CAMPAIGN_INACTIVE: 'CAMPAIGN_INACTIVE',
  DESTINATION_INVALID: 'DESTINATION_INVALID',
  DESTINATIONS_IDENTICAL: 'DESTINATIONS_IDENTICAL',
  DESTINATION_NOT_HTTPS: 'DESTINATION_NOT_HTTPS',
  DESTINATION_LOOP: 'DESTINATION_LOOP',
  ALTERNATIVE_MISSING: 'ALTERNATIVE_MISSING',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  BUDGET_EXHAUSTED: 'BUDGET_EXHAUSTED',
  JEV_UNAVAILABLE: 'JEV_UNAVAILABLE',
  JEV_TIMEOUT: 'JEV_TIMEOUT',
  JEV_INVALID_RESPONSE: 'JEV_INVALID_RESPONSE',
  CHALLENGE_UNAVAILABLE: 'CHALLENGE_UNAVAILABLE',
  DB_UNAVAILABLE: 'DB_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ApiErrorSchema = z.object({
  code: z.string(),
  message: z.string(),
  details: z.record(z.unknown()).optional(),
});
export type ApiError = z.infer<typeof ApiErrorSchema>;
